services:
  - type: web
    name: recepcaotb
    env: docker
    region: sao
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: NODE_VERSION
        value: 18.x
    healthCheckPath: /api/health
    autoDeploy: true
    plan: free
